####################################################################
# BINARY SENSORS

#binary_sensor:

####################################################################
# Template Binary Sensor
# see https://esphome.io/components/binary_sensor/template.html

# sensor spy mode
- platform: template
  name: ${template_binary_sensor_spy_mode_name}
  id: ${template_binary_sensor_spy_mode_id}
# ############################################################
#  END OF FILE
# ############################################################
