# ############################################################
#
#  Binary sensors
#
# ############################################################

#binary_sensor:

###########################################################################
# group the DW sensors in L2 kitchen
###########################################################################
- platform: group
  name: ZB_DW_L2_kitchen_contacts
  entities:
    - binary_sensor.zb_dw_l2_kitchen_01_contact

- platform: group
  name: ZB_DW_L2_kitchen_tamper
  entities:
    - binary_sensor.zb_dw_l2_kitchen_01_tamper

- platform: group
  name: ZB_DW_L2_kitchen_battery_low
  entities:
    - binary_sensor.zb_dw_l2_kitchen_01_battery_low
# ############################################################
#  END OF FILE
# ############################################################
