####################################################################
# SWITCHES

#############################
# spy mode switch
- platform: template
  name: ${template_switch_spy_mode_name}
  id: ${template_switch_spy_mode_id}
  optimistic: true
  restore_mode: ALWAYS_OFF
  on_turn_on:
    then:
      - delay: !secret DELAY_30MIN
      - switch.turn_off: ${template_switch_spy_mode_id}
  #     - logger.log: "switch ${template_switch_spy_mode_name} switched on."
  #     # - binary_sensor.template.publish:
  #     #     id: ${template_binary_sensor_spy_mode_id}
  #     #     state: true
  # on_turn_off:
  #   then:
  #     - logger.log: "switch ${template_switch_spy_mode_name} switched off."
  #     # - binary_sensor.template.publish:
  #     #     id: ${template_binary_sensor_spy_mode_id}
  #     #     state: false

# ############################################################
#  END OF FILE
# ############################################################

