####################################################################
# SWITCHES

#############################
# spy mode switch
- platform: template
  name: ${template_switch_spy_mode_name}
  id: ${template_switch_spy_mode_id}
  optimistic: true
  restore_mode: ALWAYS_OFF
  on_turn_on:
    then:
    # - logger.log: "switch ${template_switch_spy_mode_name} switched on SSR1/SSR2 will be turned off."

    # turn off SSR01 in case it is on
    - switch.turn_off: ${ssr01_id}

    # turn off SSR02 (kitchen) in case it is on
    - switch.turn_off: ${ssr02_id}

    # spy mode is active for 30 minutes, then it is automatically switched off
    - delay: !secret DELAY_30MIN
    - switch.turn_off: ${template_switch_spy_mode_id}
    
    # - logger.log: "switch ${template_switch_spy_mode_name} switched off."

# ############################################################
#  END OF FILE
# ############################################################

