#!/bin/bash

##########################################################################################
#
#  this script searches for a string in yaml files contained in the 
#  root directory of the repository and its sub directories
#
##########################################################################################

SEARCH_STRING=$1

BNAME=`basename $0 .sh`
DNAME=`dirname $0`
if [ "$DNAME" == "." ];then
 DNAME="`pwd`"
fi

. ${DNAME}/scriptConfig

cd ${HA_PATH}

find . -name \*.yaml 2> /dev/null | \
  grep -v _unused 2> /dev/null | \
  xargs grep -ni "$SEARCH_STRING" | \
  sort
