#!/bin/bash

##########################################################################################
#
#  this script generates the input_selects
#  for choosing the sunset & sunrise based theme settings
#
##########################################################################################

BNAME=`basename $0 .sh`
DNAME=`dirname $0`
if [ "$DNAME" == "." ];then
 DNAME="`pwd`"
fi

. ${DNAME}/scriptConfig

if [ ! -d ${HA_PATH} ];then
  echo "ERROR: directory does not exist: ${HA_PATH}"
  exit 99
fi

SRC_DIR="${HA_PATH}/themes"
TGT_FILE="${HA_PATH}/conf/input_select/theme_select.yaml"

echo "HA_PATH = ${HA_PATH}"
echo "SRC_DIR = ${SRC_DIR}"
echo "TGT_FILE = ${TGT_FILE}"


function get_themes {
  # parameter 1: unused
  # parameter 2: debugging output yes/no (1==yes)

  if [ $2 -eq 1 ];then
    echo "function get_themes got called"
    echo "PARAM 1 = $1"
    echo "PARAM 2 = $2"
  fi

  cd ${SRC_DIR}

  PLACEHOLDER_FOR_SPACE="@"
  for theme in `grep "^[0-9,A-Z,a-z]" */*.yaml | cut -f 2 -d ":" | sort | tr " " ${PLACEHOLDER_FOR_SPACE}`
  do
    realtheme=`echo "$theme" | tr ${PLACEHOLDER_FOR_SPACE} " "`
    echo "      - ${realtheme}" >> ${TGT_FILE}
    if [ $2 -eq 1 ];then
      # debugging names
      echo "  - $realtheme"
    fi
  done

}


echo "\
##########################################################################################
#
# Drop downs (input selects)
#
# Attention: This file is generated by a script. Do not edit!
# Last generation of this file took place at `date +%Y%m%d_%H%M%S`" \
> ${TGT_FILE}
echo "\
##########################################################################################

# input_select:
  theme:
    name: 'Select Theme'
    icon: mdi:palette
    options:
      - 'please select'" \
>> ${TGT_FILE}
get_themes 9 1
echo "\
    initial: 'please select'" >> ${TGT_FILE}
echo "\

  set_sunrise_theme:
    name: 'Select Sunrise theme'
    icon: mdi:weather-sunny
    options:" >> ${TGT_FILE}
get_themes 9 0
#get_themes 1
echo "\

  set_sunset_theme:
    name: 'Select Sunset theme'
    icon: mdi:weather-night
    options:" >> ${TGT_FILE}
get_themes 9 0
#get_themes 1 0

echo "\

####################################################################
# EOF
####################################################################
" >> ${TGT_FILE}

