##########################################################################################
#
#  this script generates input_selects 
#
##########################################################################################

BNAME=`basename $0 .sh`
DNAME=`dirname $0`
if [ "$DNAME" == "." ];then
 DNAME="`pwd`"
fi

. ${DNAME}/scriptConfig

if [ ! -d ${HA_PATH} ];then
  echo "ERROR: directory does not exist: ${HA_PATH}"
  exit 99
fi

SRC_DIR="${HA_PATH}/themes"
TGT_FILE="${HA_PATH}/conf/input_selects/themes.yaml"

function get_themes {
  cd ${SRC_DIR}
  
  if [ $1 -eq 1 ];then
    for theme in `grep "^[a-z]" * | cut -f 1 -d "." | sort | head -n1`
    do
      printf "    initial: '%s'\n" $theme >> ${TGT_FILE}
    done
  else
    for theme in `grep "^[a-z]" * | cut -f 1 -d "." | sort`
    do
      printf "      - '%s'\n" $theme >> ${TGT_FILE}
    done
  fi
}


echo "\
##########################################################################################
#
# Drop downs (input selects)
#
# Attention: This file is generated by a script. Do not edit!
#
##########################################################################################

# input_select:
  theme:
    name: 'Select Theme'
    icon: mdi:palette
    options:
      - 'please select'" \
> ${TGT_FILE}
get_themes 9
echo "\
    initial: 'please select'" >> ${TGT_FILE}
echo "\

  set_sunrise_theme:
    name: 'Select Sunrise theme'
    icon: mdi:weather-sunny
    options:" >> ${TGT_FILE}
get_themes 9
get_themes 1
echo "\

  set_sunset_theme:
    name: 'Select Sunset theme'
    icon: mdi:weather-night
    options:" >> ${TGT_FILE}
get_themes 9
get_themes 1

echo "\

####################################################################
# EOF
####################################################################
" >> ${TGT_FILE}
