####################################################################
# OVERWRITE COMMON SUBSTITUTIONS

# if there are no overrides the dummy value comes in handy ;-)
# dummy_value: "dummy value"

# AHT20 sensor
aht20_01_temp_name: $friendly_name AHT20 T 01
aht20_01_hum_name: $friendly_name AHT20 H 01
aht20_01_address: 0x38
aht20_01_variant: AHT20
aht20_01_temp_unit: "°C"
aht20_01_hum_unit: "%"
aht20_01_temp_id: ${friendly_id}_AHT20_T_01
aht20_01_hum_id: ${friendly_id}_AHT20_H_01
aht20_01_update_interval: 600s

# bmp280 sensor for temperature and pressure
bmp280_01_temp_name: $friendly_name BMP280 T 01
bmp280_01_temp_id: ${friendly_id}_BMP280_T_01
bmp280_01_address: 0x77
bmp280_01_pressure_name: $friendly_name BMP280 P 01
bmp280_01_pressure_id: ${friendly_id}_BMP280_P_01
bmp280_01_temp_unit: "°C"
bmp280_01_pressure_unit: "hPa"
bmp280_01_update_interval: 600s

# GPS related definitions
# the update interval for the GPS sensor
gps_update_interval: 600s
gps_id: ${friendly_id}_gps
gps_latitude_name: $friendly_name GPS latitude
gps_latitude_id: ${friendly_id}_gps_latitude_id
gps_longitude_name: $friendly_name GPS longitude
gps_longitude_id: ${friendly_id}_gps_longitude_id
gps_altitude_name: $friendly_name GPS altitude
gps_altitude_id: ${friendly_id}_gps_altitude_id
gps_speed_name: $friendly_name GPS speed
gps_speed_id: ${friendly_id}_gps_speed_id
gps_course_name: $friendly_name GPS course
gps_course_id: ${friendly_id}_gps_course_id
gps_satellites_name: $friendly_name GPS visible satellites
gps_satellites_id: ${friendly_id}_gps_satellites_id
gps_hdop_name: $friendly_name GPS HDOP
gps_hdop_id: ${friendly_id}_gps_hdop_id

# log level for this device, default is "INFO", but for debugging you might want to set it to "DEBUG"
log_level: !secret LOG_LEVEL_DEBUG
####################################################################
# EOF
####################################################################
