####################################################################
# ESP32-2432S028R aka CYD - onboard LED

# light:
  # display backlight control
  - platform: monochromatic
    output: backlight_pwm
    name: Display Backlight
    id: display_backlight
    restore_mode: ALWAYS_ON

  # RGB LED control
  - platform: rgb
    name: "RGB LED"
    id: rgb_led
    red: output_red
    green: output_green
    blue: output_blue

####################################################################
# EOF
####################################################################
