####################################################################
# ESP32C3 - onboard LED

# light:
  - platform: binary
    output: $esp32c3_onboard_led_id
    name: $esp32c3_onboard_led_name

####################################################################
# EOF
####################################################################
