####################################################################
# TIME

#time:
  - platform: homeassistant
    id: esphome_time
    timezone: "Europe/Berlin"

####################################################################
# EOF
####################################################################
