####################################################################
# TIME

#time:
  - platform: gps
    id: esphome_time
    timezone: "Europe/Berlin"
    on_time_sync:
      if:
        condition:
          time.has_time:
        then:
          - logger.log: "GPS Time Updated"
        else:
          - logger.log: "GPS Time Sync Failed"

####################################################################
# EOF
####################################################################
