####################################################################
# TIME

#time:
  - platform: sntp
    id: esphome_time
    timezone: Europe/Berlin
    servers:
     - 0.pool.ntp.org
     - 1.pool.ntp.org
     - 2.pool.ntp.org
####################################################################
# EOF
####################################################################
