####################################################################
# text sensor config for ESP32-2432S028R aka CYD --- with onboard ESP32
####################################################################
# text_sensor:
  - platform: lvgl
    widget: lbl_page_location_time_start
    name: "ts_lbl_page_location_time_start"
  - platform: lvgl
    widget: lbl_page_location_temp_01
    name: "ts_lbl_page_location_temp_01"
  - platform: lvgl
    widget: lbl_page_location_hum_01
    name: "ts_lbl_page_location_hum_01"
  - platform: lvgl
    widget: lbl_page_location_time_end
    name: "ts_lbl_page_location_time_end"
####################################################################
# EOF
####################################################################
