####################################################################
# display config for ESP32-2432S028R aka CYD --- with onboard ESP32
####################################################################

# display:

# the following config seems to be the working one w/ colour
####################################################################
# config from https://community.home-assistant.io/t/faulty-cyd-or-config-error/908986
# lambda added from below
####################################################################

# during compilation, the following warning is shown:
# WARNING The 'ili9xxx' component is deprecated, it is recommended to use 'mipi_spi' instead.

- platform: mipi_spi
  id: esp_display
  model: ESP32-2432S028-9342
  spi_id: tft
  cs_pin: GPIO15
  dc_pin: GPIO2
  #invert_display: true (changed to below with ESPhome 2023.12.0)
  invert_colors: false
  # for color_palette: seee https://esphome.io/components/display/ili9xxx/#configuration-variables
  # color_palette: 8BIT
  # color_palette: NONE
  color_order: rgb
  #update_interval: never  # The interval to re-draw the screen. Defaults to 1s.
  #auto_clear_enabled: false
  # rotation: valid values: 0, 90, 180 or 270. 180 equals to antenna on the left side
  # pay attention to the touchscreen, swap_xy: might be changed accordingly
  # after changing the rotation to 180, ...
  #   - having rotation: in display: does not get valitaded, so we put it into lvgl: config  
  #   - swap_xy: true is needed for the touchscreen to work correctly in landscape mode
  # rotation: ${cyd_display_rotation} 
  dimensions:
   width: ${cyd_display_width_320}
   height: ${cyd_display_height_240}
   #show_test_card: true

# ############################################################
#  END OF FILE
# ############################################################
