####################################################################
# UART ESP32-CYD
####################################################################

# uart:
  - id: ${uart01_esp32_gps_id}
    tx_pin: GPIO21
    rx_pin: GPIO35
    baud_rate: 9600
# ############################################################
#  END OF FILE
# ############################################################

