####################################################################
# UART ESP32
####################################################################

# uart:
  - id: ${uart01_esp32_gps_id}
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 9600
# ############################################################
#  END OF FILE
# ############################################################

