# ############################################################
#
#  Binary sensors
#
# ############################################################

#binary_sensor:

###########################################################################
# handle the times for the start and end of the day for the location 
# tracking, as well as the button states for the same
###########################################################################
  # ---------------------------------------------------------------------------
  # end of the day for location tracking, e.g. when arriving at a poarking lot in the evening
  - platform: lvgl
    name: "Location day end"
    id: location_day_end
    widget: lbl_btn_day_end
    on_state:
      - if:
          condition:
            - binary_sensor.is_on: location_day_end
          then:
            - lambda: |-
               ESP_LOGD("binary_sensor", "Location day end is ON");
            - lvgl.widget.update:
                id: lbl_btn_day_end
                text_color: default_btn_txt_checked_color
            - lvgl.label.update:
                id: lbl_page_location_time_end
                text:
                  format: "%02d:%02d:%02d"
                  args: [ 'id(esphome_time).now().hour', 
                          'id(esphome_time).now().minute', 
                          'id(esphome_time).now().second' ]
            # have a short delay so the times can be seen on the display
            # before clearing the fields for the start/poi/end time, so they are ready for the next day
            - delay: 4000ms
            # clearing the fields for the start/poi/end time, so they are ready for the next day
            - lvgl.label.update:
                id: lbl_page_location_time_start
                text: "Time\nStart"
            - lvgl.label.update:
                id: lbl_page_location_poi
                text: "Time\nPOI"
            - lvgl.label.update:
                id: lbl_page_location_time_end
                text: "Time\nEnd"
          else:
            - lambda: |-
               ESP_LOGD("binary_sensor", "Location day end is OFF");
            - lvgl.widget.update:
                id: lbl_btn_day_end
                text_color: default_btn_txt_color
# ############################################################
#  END OF FILE
# ############################################################
