# ############################################################
#
#  Binary sensors
#
# ############################################################

#binary_sensor:

###########################################################################
# handle the times for the start and end of the day for the location 
# tracking, as well as the button states for the same
###########################################################################
  # ---------------------------------------------------------------------------
  # start of the day for location tracking, e.g. when leaving home in the morning
  - platform: lvgl
    name: "Location day start"
    id: location_day_start
    widget: lbl_btn_day_start
    on_state:
      - if:
          condition:
            - binary_sensor.is_on: location_day_start
          then:
            - lambda: |-
                ESP_LOGD("binary_sensor", "Location day start is ON");
            - lvgl.widget.update:
                id: lbl_btn_day_start
                text_color: default_btn_txt_checked_color
            - lvgl.label.update:
                id: lbl_page_location_time_start
                text:
                  format: "%s\n  %s"
                  args: [ 'id(${location_now_time_id}).state', 'id(${location_now_date_id}).state' ]
          else:
            - lambda: |-
               ESP_LOGD("binary_sensor", "Location day start is OFF");
            - lvgl.widget.update:
                id: lbl_btn_day_start
                text_color: default_btn_txt_color
# ############################################################
#  END OF FILE
# ############################################################
