# ############################################################
# Camera RWorld01 related automations
# ############################################################

# ############################################################
# Camera RWorld01 snapshot reenabling
# ############################################################
- alias: Camera RWorld01 snapshot reenabling
  id: "07b3755b-d694-4cb8-9f1d-e2310d2546c5"
  initial_state: true
  # --------------------- TRIGGER ---------------------
  triggers:
    - trigger: state
      entity_id: input_boolean.cam_rworld1_snapshot_enabled
      to: "true"
      for:
        minutes: 1
        seconds: 30
  # -------------------- CONDITIONS -------------------
  condition: []
  # --------------------- ACTIONS ---------------------
  action:
    # --------------------- END COOLDOWN ---------------------
    - action: input_boolean.turn_on
      target:
        entity_id: input_boolean.cam_rworld1_snapshot_enabled
############################################################
#  END OF FILE
# ############################################################
