# ############################################################
#
#  templated text sensor
#
# ############################################################

# text_sensor:
  - platform: template
    name: ${loc_now_timedate_name}
    id: ${loc_now_timedate_id}
    lambda: |-
      if (id(esphome_time).now().is_valid()) {
        return (id(esphome_time).now().strftime("%H:%M:%S\n%d.%m.%y"));
      } else {
        return ( "NoTime\nNoDate" );
      }
    update_interval: ${update_interval_template_text_sensor_loc_now_timedate}
# ############################################################
#  END OF FILE
# ############################################################


