####################################################################
# DISPLAY INTERVAL

# show the next page every x seconds, and update the display
  - interval: 1s
    then:
      - lvgl.label.update:
          id: lbl_page_location_time
          text:
            format: "%s"
            args: [ 'id(${loc_now_timedate_id}).state.c_str()' ]
      - lambda: |-
          ESP_LOGD("text_sensor", "loc_now_timedate: %s", id(${loc_now_timedate_id}).state.c_str());

# ############################################################
#  END OF FILE
# ############################################################
