####################################################################
# DISPLAY INTERVAL

# show the next page every x seconds, and update the display
  - interval: 1s
    then:
      - lvgl.label.update:
          id: lbl_page_location_time
          text:
            format: "%s\n  %s"
            args: [ 'id(${location_now_time_id}).state.c_str()', 
                    'id(${location_now_date_id}).state.c_str())' 
                  ]
      - lambda: |-
          ESP_LOGD("text_sensor", "time_now: %s", id(${location_now_time_id}).state.c_str());

# ############################################################
#  END OF FILE
# ############################################################
