# ############################################################
#
#  templated sensor
#
# ############################################################

# sensor:
  - platform: template
    name: ${local_time_timestamp_name}
    id: ${local_time_timestamp_id}
    lambda: |-
      if (id(esphome_time).now().is_valid()) {
        return (id(esphome_time).now().timestamp);
      } else {
        return ( 0 );
      }
    update_interval: ${update_interval_template_text_sensor_local_time_timestamp}
# ############################################################
#  END OF FILE
# ############################################################
