####################################################################
# BINARY SENSORS

#binary_sensor:

####################################################################
# Binary Sensors from home assistant
# see https://esphome.io/components/binary_sensor/homeassistant/

# DW sensor groups from home assistant for storage
- platform: homeassistant
  name: $homeassistant_binary_sensor_windows_group_storage_name
  id: $homeassistant_binary_sensor_windows_group_storage_id
  entity_id: $homeassistant_binary_sensor_windows_group_storage_entity_id
# ############################################################
#  END OF FILE
# ############################################################
