####################################################################
# WIFI - multiple networks
####################################################################

# ---------------------------------------------------------------------
# WiFi settings
wifi:
  networks:
    # WIFI_L99_SSID is a not existing SSID, so it will not be connected to this network
    # it will be used to test the fallback hotspot (captive portal) available in case 
    # of no connection to any of the other networks at http://192.168.4.1/
    - ssid: !secret WIFI_L99_SSID
      password: !secret WIFI_L99_PW
    # - ssid: !secret WIFI_L95_SSID
    #   password: !secret WIFI_L95_PW
    # - ssid: !secret WIFI_L96_SSID
    #   password: !secret WIFI_L96_PW
    # - ssid: !secret WIFI_L0_SSID
    #   password: !secret WIFI_L0_PW
    # - ssid: !secret WIFI_L2_SSID
    #   password: !secret WIFI_L2_PW
    # - ssid: !secret WIFI_L91_SSID
    #   password: !secret WIFI_L91_PW
    # - ssid: !secret WIFI_L92_SSID
    #   password: !secret WIFI_L92_PW
  domain: !secret WIFI_DOMAIN
  min_auth_mode: WPA2  # Reject WPA-only networks
  on_connect:
    then:
      - lvgl.widget.show: lbl_wifi_status
      - lvgl.label.update:
          id: lbl_ip_address
          text:
            format: "IP Address: %s"
            args: [ 'id(${wifi_conn_ip_addr_id}).state.c_str()' ]      
      # - lvgl.label.update:
      #     id: lbl_wait_booting_up
      #     text: "Please push here to continue..."
      # - lambda: |-
      #     id(btn_wifi_status).set_hidden(false);
      #     ESP_LOGD("wifi", "Connected to WiFi network: %s", WiFi.SSID().c_str());
      - lambda: |-
          ESP_LOGD("wifi", "Connected to WiFi network: %s", WiFi.SSID().c_str());
  on_disconnect:
    then:
      - lvgl.widget.hide: lbl_wifi_status
      - lvgl.label.update:
          id: lbl_ip_address
          text: "IP Address: not connected"
      - lvgl.label.update:
          id: lbl_wait_booting_up
          text: "Waiting for WiFi..."
      - lvgl.widget.show: boot_screen
      # - lambda: |-
      #     id(btn_wifi_status).set_hidden(true);
      #     ESP_LOGD("wifi", "Disconnected from WiFi network");
      - lambda: |-
          ESP_LOGD("wifi", "Disconnected from WiFi network");
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}_Hotspot
    password: !secret AP_PASSWORD_ESP322432S028R_AKA_CYD

# ############################################################
#  END OF FILE
# ############################################################
