# ############################################################
#
#  templated text sensor
#
# ############################################################

# text_sensor:
  - platform: template
    name: ${loc_now_time_name}
    id: ${loc_now_time_id}
    lambda: |-
      if (id(esphome_time).now().is_valid()) {
        return (id(esphome_time).now().strftime("%H:%M:%S"));
      } else {
        return ( "NoTime" );
      }
    update_interval: 1s
# ############################################################
#  END OF FILE
# ############################################################


