####################################################################
# TEXT SENSORS

#text_sensor:

####################################################################
# ld2410c sensor
  - platform: ld2410
    version:
      name: "LD2410 Firmware Version"
    mac_address:
      name: "LD2410 Bluetooth MAC"
# ############################################################
#  END OF FILE
# ############################################################
