# ############################################################
#
#  Notebook charging
#
# ############################################################

# ############################################################
# Notebook charging on
# ############################################################
- alias: Notebook charging on
  id: "019fc410-93d3-77f6-bbee-f8a1d1ca8732"
  mode: single
  initial_state: true

  # --------------------- TRIGGER ---------------------
  triggers:
    - trigger: time
      at: "06:01:00"

  # -------------------- CONDITIONS -------------------
  condition: []

  # --------------------- ACTIONS ---------------------
  action:
    # ------------------- SEND NOTIFICATION -------------------
    - action: switch.turn_on
      entity_id: switch.zb_plug_l2_misc_02

# ############################################################
# Notebook charging off
# ############################################################
- alias: Notebook charging off
  id: "019fc415-145d-702d-8e30-b3081baf87a0"
  mode: single
  initial_state: true

  # --------------------- TRIGGER ---------------------
  triggers:
    - trigger: time
      at: "07:01:00"

  # -------------------- CONDITIONS -------------------
  condition: []

  # --------------------- ACTIONS ---------------------
  action:
    # ------------------- SEND NOTIFICATION -------------------
    - action: switch.turn_off
      entity_id: switch.zb_plug_l2_misc_02
# ############################################################
#  END OF FILE
# ############################################################
