# ############################################################
#
#  Notebook charging
#
# ############################################################

# ############################################################
# Notebook charging from 6am for 1 hour
# ############################################################
- alias: Notebook charging
  id: "019fc410-93d3-77f6-bbee-f8a1d1ca8732"
  mode: single
  initial_state: true

  # --------------------- TRIGGER ---------------------
  triggers:
    - trigger: time
      at: "06:01:00"
    - trigger: time
      at: "11:01:00"
    - trigger: time
      at: "17:01:00"
    - trigger: time
      at: "22:01:00"

  # -------------------- CONDITIONS -------------------
  condition: []

  # --------------------- ACTIONS ---------------------
  action:
    # ------------------- SEND NOTIFICATION -------------------
    - action: switch.turn_on
      entity_id: switch.zb_plug_l2_misc_02
    - delay: "1:00"
    - action: switch.turn_off
      entity_id: switch.zb_plug_l2_misc_02
# ############################################################
#  END OF FILE
# ############################################################
