# ############################################################
#
#  Window contact detected open window
#
# ############################################################

# ############################################################
#  Window contact detected open window
# ############################################################
- alias: Window contact detected open window
  id: "48ba3366-08e4-4885-bd8a-94b090585307"
  description: "This automation handles L2 TRV open window conditions"
  mode: single
  max_exceeded: silent

  initial_state: true
  # --------------------- TRIGGER ---------------------
  triggers:
    # if the group zb_dw_l2_bedroom_contact goes to "on"
    - trigger: state
      id: "zb_dw_l2_bedroom_contact"
      entity_id: binary_sensor.zb_dw_l2_bedroom_contact
      to: "on"
  # -------------------- CONDITIONS -------------------
  condition:
    - alias: "Allowing the switching of trv hvac mode based on enable switch"
      condition: state
      entity_id: input_boolean.trv_enable_hvac_mode_switching
      state: "on"
  # --------------------- ACTIONS ---------------------
  actions:
    # ------------- TRV GETS SWITCHED OFF / BACK TO AUTO ----------
    - action: climate.set_hvac_mode
      target:
        entity_id: climate.zb_trv_bedroom_l2
      data:
        hvac_mode: "off"
    # 20 minutes delay till return to auto mode
    - delay: "00:20"
    - action: climate.set_hvac_mode
      target:
        entity_id: climate.zb_trv_bedroom_l2
      data:
        hvac_mode: "auto"
# ############################################################
#  END OF FILE
# ############################################################
