# ############################################################
#
#  Set the state of the ZB plug UH depending on the state of the switch / the current state
#
# ############################################################

# ############################################################
#  Set the state of the ZB plug UH to undefined
# ############################################################
- alias: Set the state of the ZB plug UH to undefined
  id: "e89441ae-a46d-4ed0-87bd-7458d94a5e71"
  description: "This automation sets the state of the ZB plug UH to undefined"
  mode: single
  initial_state: true
  # --------------------- TRIGGER ---------------------
  triggers:
    - trigger: template
      value_template: "{{ is_state('binary_sensor.zb_charger_uh_functionality_charger_off', 'on') }}"
      for:
        minutes: 3
        seconds: 0
  # -------------------- CONDITIONS -------------------
  # none whatsoever
  condition: []
  # --------------------- ACTIONS ---------------------
  action:
    - action: input_select.select_option
      target:
        entity_id: input_select.zb_charger_uh_state_current
      data:
        option: "{{ states('input_text.zb_charger_state_current_state_is_undefined') }}"

# ############################################################
#  Set the state of the ZB plug UH to charging
# ############################################################
- alias: Set the state of the ZB plug UH to charging
  id: "019fae93-2580-7069-accf-ac4d790775af"
  description: "This automation sets the state of the ZB plug UH to charging"
  mode: single
  initial_state: true
  # --------------------- TRIGGER ---------------------
  triggers:
    - trigger: template
      value_template: "{{ is_state('binary_sensor.zb_charger_uh_functionality_athome_charger_on_state_undefined', 'on') }}"
  # -------------------- CONDITIONS -------------------
  # none whatsoever
  condition: []
  # --------------------- ACTIONS ---------------------
  action:
    - action: input_select.select_option
      target:
        entity_id: input_select.zb_charger_uh_state_current
      data:
        option: "{{ states('input_text.zb_charger_state_current_normal_charging_in_progress') }}"
# ############################################################
#  END OF FILE
# ############################################################
