####################################################################
####################################################################
#
# DEVICE: espnow_slave
#
####################################################################
####################################################################

####################################################################
# DESCRIPTION
####################################################################
#
# Purpose:
#   - This microcontroller uses ESP-NOW to send commands to 
#     the slave and (one day) to receive GPS data from the slave.
#
# Hardware:
#   - 1 ESP32 development board
#
# Automation:
#   - undetermined
#
# WiFi:
#   - no WiFi connection, only ESP-NOW communication with the slave
#
# Input:
#   - none
#
# Output
#   - 1 onboard LED to indicate sent commands to the slave
#

###################### PACKAGES CONFIGURATION ######################
# naming conventions which override common behaviour

esphome:
  name: test-com-offline-master
  friendly_name: test communication offline - master

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api: !include conf/common/networking/api.yaml
# api:
#   encryption:
#     key: "___"

ota: !include conf/common/networking/ota.yaml
# ota:
#   - platform: esphome
#     password: "___"

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-Com-Offline-Master"
    password: "12345678"

captive_portal:

espnow:
  peers:
    - !secret ESPNOW_MAC_ESPNOW_SLAVE  # slave MAC
  on_receive:
    address: !secret ESPNOW_MAC_ESPNOW_SLAVE
    then:
      - if:
          condition:
            lambda: 'return size > 0 && data[0] == 0x01;'
          then:
            - output.turn_on: led
            - logger.log: "ESPNow: Received data Power On"
      - if:
          condition:
            lambda: 'return size > 0 && data[0] == 0x00;'
          then:
            - output.turn_off: led
            - logger.log: "ESPNow: Received data Power Off"


binary_sensor:
  - platform: gpio
    pin: GPIO4
    name: "Button"
    on_press:
      then:
        - espnow.send:
            address: !secret ESPNOW_MAC_ESPNOW_SLAVE
            data: [0x01]  # Turns on the LED on the slave
        - logger.log: "Sent data Power On"
        - output.turn_on: led
        - delay: 0.5s
        - espnow.send:
            address: !secret ESPNOW_MAC_ESPNOW_SLAVE
            data: [0x00]  # Turns off the LED on the slave
        - logger.log: "Sent data Power Off"
        - output.turn_off: led

output:
  - platform: gpio
    pin: GPIO2
    id: led
    inverted: False
####################################################################
# EOF
####################################################################
