####################################################################
####################################################################
#
# DEVICE: espnow_slave
#
####################################################################
####################################################################

####################################################################
# DESCRIPTION
####################################################################
#
# Purpose:
#   - This microcontroller uses ESP-NOW to receive commands from 
#     the master and (one day) to send GPS data to the master.
#
# Hardware:
#   - 1 ESP32 development board
#   - 1 GPS module
#
# Automation:
#   - undetermined
#
# WiFi:
#   - no WiFi connection, only ESP-NOW communication with the master
#
# Input:
#   - GPS data
#
# Output
#   - 1 onboard LED to indicate received commands from the master
#

###################### PACKAGES CONFIGURATION ######################
# naming conventions which override common behaviour

substitutions:
  <<: !include conf/substitutions/device_specific/espnow_slave.yaml
  <<: !include conf/substitutions/overwrites/espnow_slave.yaml

# esphome:
#   name: test-com-offline-slave
#   friendly_name: test communication offline - slave

# esp32:
#   board: esp32dev
#   framework:
#     type: esp-idf

packages:
  substitutions_common: !include conf/common/packages/substitutions/common.yaml
  device_base_common: !include conf/common/packages/device_base_esp32.yaml
  # wifi_common: !include conf/common/networking/wifi_multiple_networks_dhcp_ip.yaml

# Enable logging
logger:

# Enable Home Assistant API
api: !include conf/common/networking/api.yaml

ota: !include conf/common/networking/ota.yaml

wifi:
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-Com-Offline-Slave"
    password: "12345678"

captive_portal:

uart: !include conf/common/device/uart01_esp32_gps.yaml

gps:
  id: ${friendly_id}_gps
  uart_id: ${uart01_esp32_gps_id}
  latitude:
    name: "GPS Latitude"
    id: gps_latitude
  longitude:
    name: "GPS Longitude"
    id: gps_longitude
  altitude:
    name: "GPS Altitude"
    id: gps_altitude
  speed:
    name: "GPS Speed"
    id: gps_speed
  course:
    name: "GPS Course"
    id: gps_course
  satellites:
    name: "GPS Visible Satellites"
    id: gps_satellites
  hdop:
    name: "GPS HDOP"
    id: gps_hdop
  update_interval: 20s

time:
  - platform: gps
    id: gps_time
    on_time_sync:
      if:
        condition:
          time.has_time:
        then:
          - logger.log: "GPS Time Updated"
        else:
          - logger.log: "GPS Time Sync Failed"

espnow:
  peers:
    - !secret ESPNOW_MAC_ESPNOW_MASTER # master MAC 
  on_receive:
    address: !secret ESPNOW_MAC_ESPNOW_MASTER
    then:
      - if:
          condition:
            lambda: 'return size > 0 && data[0] == 0x01;'
          then:
            - output.turn_on: led
            - logger.log: "ESPNow: Received data Power On"
            - delay: 2s
            - espnow.send:
                address: !secret ESPNOW_MAC_ESPNOW_MASTER
                data: [0x01]
            - logger.log: "ESPNow: Sent data Power On"
      - if:
          condition:
            lambda: 'return size > 0 && data[0] == 0x00;'
          then:
            - output.turn_off: led
            - logger.log: "ESPNow: Received data Power Off"
            - delay: 2s
            - espnow.send:
                address: !secret ESPNOW_MAC_ESPNOW_MASTER
                data: [0x00]
            - logger.log: "ESPNow: Sent data Power Off"

output:
  - platform: gpio
    pin: GPIO2
    id: led
    inverted: False

interval:
- interval: 10seconds
  then:
    - logger.log:
        format: "GPS updated latitude / longitude: %.1f,%.1f"
        args: [ 'id(gps_latitude).state', 'id(gps_longitude).state' ]
    - output.turn_on: led
    - delay: 2s
    - output.turn_off: led

    # if:
    #   condition:
    #     time.has_time:
    #   then:
    #     - logger.log:
    #       format: "GPS updated to %.1f and humidity %.1f"
    #       args: [ 'id(gps_latitude).state', 'id(gps_longitude).state' ]
    #     # - logger.log: "GPS updated to Latitude: ${latitude}, Longitude: ${longitude}, Altitude: ${altitude}, Speed: ${speed}, Course: ${course}, Satellites: ${satellites}, HDOP: ${hdop}, Fix Type: ${fix_type}"
####################################################################
# EOF
####################################################################
