####################################################################
# ESP32C3 - onboard LED

# output:
  - platform: gpio
    pin: GPIO8
    id: $esp32c3_onboard_led_id
    # "inverted: false" works for l2lounge09
    inverted: false

####################################################################
# EOF
####################################################################
