####################################################################
# ESP32C3 - onboard LED

# output:
  - platform: gpio
    pin: GPIO8
    id: $esp32c3_onboard_led_id

####################################################################
# EOF
####################################################################
