####################################################################
# DEVICE SPECIFIC SUBSTITUTIONS

# device definitions
device_name: l9lorry01d
device_comment: Level 9 Lorry 01D ESP32-2432S028R aka CYD
device_area: L9

device_platform: ESP32
wifi_static_ip: 192.168.178.39

# The ESP32-2432S028R uses a standard ESP32-WROVER, 
# so we use the esp32dev defintion here with the Arduino framework
device_board: esp32dev
device_framework: arduino

# the friendly name and id
friendly_name: ""
friendly_id: ""

# display
display_id: cyd_display

# template text sensor
loc_starttime_name: $friendly_name Location time start
loc_starttime_id: ${friendly_id}_loc_starttime_id
loc_startdate_name: $friendly_name Location date start
loc_startdate_id: ${friendly_id}_loc_startdate_id
loc_poitime_name: $friendly_name Location time poi
loc_poitime_id: ${friendly_id}_loc_poitime_id
loc_poidate_name: $friendly_name Location date poi
loc_poidate_id: ${friendly_id}_loc_poidate_id
loc_endtime_name: $friendly_name Location time end
loc_endtime_id: ${friendly_id}_loc_endtime_id
loc_enddate_name: $friendly_name Location date end
loc_enddate_id: ${friendly_id}_loc_enddate_id
loc_now_time_name: $friendly_name Location time now
loc_now_time_id: ${friendly_id}_location_time_now_id
loc_now_date_name: $friendly_name Location date now
loc_now_date_id: ${friendly_id}_location_date_now_id
####################################################################
# EOF
####################################################################
