####################################################################
# DEVICE SPECIFIC SUBSTITUTIONS

# device definitions
device_name: l9lorry01d
device_comment: Level 9 Lorry 01D ESP32-2432S028R aka CYD
device_area: L9

device_platform: ESP32
wifi_static_ip: 192.168.178.39

# The ESP32-2432S028R uses a standard ESP32-WROVER, 
# so we use the esp32dev defintion here with the Arduino framework
device_board: esp32dev
device_framework: arduino

# the friendly name and id
friendly_name: ""
friendly_id: ""

# ${espnow_packet_transport_provider_name_01}
friendly_remote_name: ""
friendly_remote_id: ""

# display
display_id: cyd_display

# template text sensor
local_now_timedate_name: $friendly_name Location TimeDate now
local_now_timedate_id: ${friendly_id}_location_timedate_now_id

# the interval for updating the location time on the display
update_interval_label_lbl_page_location_time: 1s
update_interval_template_text_sensor_loc_now_timedate: 1s

# ---------------------------
# now up to the ESP-NOW stuff
# ---------------------------
# the ESP-NOW packet transport provider name
espnow_packet_transport_provider_name_01: l9lorry01g 

# remote sensors from ${espnow_packet_transport_provider_name_01} via ESP-NOW packet transport
remote_location_timestamp_id: ${friendly_remote_id}_location_timestamp_now_id
local_location_timestamp_id: ${friendly_id}_local_location_timestamp_id
# local_location_timestamp_name: ${friendly_name} Location Timestamp
####################################################################
# EOF
####################################################################
