####################################################################
# DEVICE SPECIFIC SUBSTITUTIONS

# device definitions
device_name: l9lorry01d
device_comment: Level 9 Lorry 01G ESP32-2432S028R aka CYD
device_area: L9

device_platform: ESP32
wifi_static_ip: 192.168.178.39

# The ESP32-2432S028R uses a standard ESP32-WROVER, 
# so we use the esp32dev defintion here with the Arduino framework
device_board: esp32dev
device_framework: arduino

# the friendly name and id
friendly_name: ""
friendly_id: ""

# display
display_id: cyd_display

# template text sensor
location_time_day_start_name: $friendly_name Location time day start
location_time_day_start_id: ${friendly_id}_location_time_day_start
location_time_day_poi_name: $friendly_name Location time day poi
location_time_day_poi_id: ${friendly_id}_location_time_day_poi
location_time_day_end_name: $friendly_name Location time day end
location_time_day_end_id: ${friendly_id}_location_time_day_end
location_time_now_name: $friendly_name Location time now
location_time_now_id: ${friendly_id}_location_time_now
####################################################################
# EOF
####################################################################
