####################################################################
# SENSORS

####################################################################
# Temperature and humidity sensor AHT20
#sensor:
  - platform: aht10
    variant: AHT20
    temperature:
      name: ${aht20_01_temp_name}
      id: ${aht20_01_temp_id}
      unit_of_measurement: ${aht20_01_temp_unit}
      on_value:
        - lvgl.label.update:
            id: lbl_page_location_centre_left_01
            text:
              format: "%.1f ${aht20_01_temp_unit}\n%.1f %%\n%.1f ${bmp280_01_pressure_unit}"
              args: [ 'id(${aht20_01_temp_id}).get_state()', 
                      'id(${aht20_01_hum_id}).get_state()', 
                      'id(${bmp280_01_pressure_id}).get_state()' ]      
    humidity:
      name: ${aht20_01_hum_name}
      id: ${aht20_01_hum_id}
      unit_of_measurement: ${aht20_01_hum_unit}
      on_value:
        - lvgl.label.update:
            id: lbl_page_location_centre_left_01
            text:
              format: "%.1f ${aht20_01_temp_unit}\n%.1f %%\n%.1f ${bmp280_01_pressure_unit}"
              args: [ 'id(${aht20_01_temp_id}).get_state()', 
                      'id(${aht20_01_hum_id}).get_state()', 
                      'id(${bmp280_01_pressure_id}).get_state()' ]      
      # on_value:
      #   then:
      #     - lvgl.label.update:
      #         id: lbl_page_location_hum_01
      #         text: !lambda return (id('sensor.l9lorry01d_lorry_aht20_h_01').state).c_str();        
      #     # - lambda: |-
      #     #     id(lbl_page_location_hum_01).set_text(to_string(x) + " ${aht20_01_hum_unit}");
    address: ${aht20_01_address}
    update_interval: ${aht20_01_update_interval}
####################################################################
# EOF
####################################################################
