####################################################################
# SENSORS

####################################################################
# BMP280 sensor for temperature and pressure
# see https://esphome.io/components/sensor/bmp280.html for details
#sensor:
  - platform: bmp280_i2c
    temperature:
      name: ${bmp280_01_temp_name}
      id: ${bmp280_01_temp_id}
      oversampling: 16x
    pressure:
      name: ${bmp280_01_pressure_name}
      id: ${bmp280_01_pressure_id}
    address: ${bmp280_01_address}
    update_interval: ${bmp280_01_update_interval}
####################################################################
# EOF
####################################################################
