####################################################################
# SENSORS

####################################################################
# BMP280 sensor for temperature and pressure
# see https://esphome.io/components/sensor/bmp280.html for details
#sensor:
  - platform: bmp280_i2c
    temperature:
      name: ${bmp280_01_temp_name}
      id: ${bmp280_01_temp_id}
      unit_of_measurement: ${bmp280_01_temp_unit}
      oversampling: 16x
      # temperature is superfluous as the AHT20 also measures temperature, 
      # but it is included for testing purposes and to have a backup in case the AHT20 fails
      # on_value:
      #   then:
      #     - lambda: |-
      #         id(lbl_page_location_temp_01).set_text(to_string(x) + " ${bmp280_01_temp_unit}");
    pressure:
      name: ${bmp280_01_pressure_name}
      id: ${bmp280_01_pressure_id}
      unit_of_measurement: ${bmp280_01_pressure_unit}
      on_value:
        - lvgl.label.update:
            id: lbl_page_location_centre_left_01
            text:
              format: "%.1f ${aht20_01_temp_unit}\n%.1f %%\n%.1f ${bmp280_01_pressure_unit}"
              args: [ 'id(${aht20_01_temp_id}).get_state()', 
                      'id(${aht20_01_hum_id}).get_state()', 
                      'id(${bmp280_01_pressure_id}).get_state()' ]      
      # on_value:
      #   - lvgl.label.update:
      #       id: lbl_page_location_pressure_01
      #       text:
      #         format: "%.0f ${bmp280_01_pressure_unit}"
      #         args: [ 'id(${bmp280_01_pressure_id}).get_state()' ]      
    address: ${bmp280_01_address}
    update_interval: ${bmp280_01_update_interval}
####################################################################
# EOF
####################################################################
