####################################################################
# SENSORS

####################################################################
# brightness sensor using ADC pin 34 on CYD (ESP32-2432S028R)
#sensor:
  - platform: adc 
    pin: 34 
    name: ${cyd_brightness_01_name}
    id: ${cyd_brightness_01_id}
    update_interval: ${cyd_brightness_01_update_interval}
####################################################################
# EOF
####################################################################
