####################################################################
# Main configuration for the LD2410C sensor

####################################################################
# Presence sensor LD2410C
# ld2410:
  id: ld2410_sensor
  uart_id: ${uart01_esp32c3_id}
####################################################################
# EOF
####################################################################
